Allow the runtime to compile even when PTG support is not possible.
ICLDisco/parsec pull request #332
Opened 2022-03-05 18:21 UTC by bosilca

At this point there is no option to disable a DSL manually, but at least the PTG support will be automatically disabled by CMake if the prerequisite (bison and flex) are not found.

Fixes #301.

Signed-off-by: George Bosilca <bosilca@icl.utk.edu>

2022-03-07 20:41 UTC, abouteiller commented on parsec/mca/device/cuda/device_cuda_module.c
> -            if(PARSEC_SUCCESS != gpu_task->stage_in? gpu_task->stage_in(gpu_task, (1U << flow->flow_index), gpu_stream): PARSEC_SUCCESS){
This changeset looks unrelated. Was it intended to be part of this PR?

2022-03-07 23:22 UTC, abouteiller commented
pr #335 is an alternative

2022-03-11 17:24 UTC, devreal approved these changes

2022-03-11 20:00 UTC, abouteiller requested changes

2022-03-11 20:32 UTC, bosilca commented on parsec/mca/device/cuda/device_cuda_module.c
> -            if(PARSEC_SUCCESS != gpu_task->stage_in? gpu_task->stage_in(gpu_task, (1U << flow->flow_index), gpu_stream): PARSEC_SUCCESS){
It is indentation and adding {}.

2022-03-11 20:34 UTC, abouteiller approved these changes

2022-03-11 20:44 UTC, merged