fix remote_dep_mpi.c
ICLDisco/parsec pull request #429
Opened 2022-09-14 18:56 UTC by cflinto

2022-09-14 19:10 UTC, devreal requested changes
This looks legit, thanks @cflinto! Please provide a proper description in the commit and make sure it's signed off (using `git commit -x`).

2022-09-14 20:33 UTC, cflinto commented
Thank you @devreal, it should be good now.

2022-09-14 22:42 UTC, therault approved these changes

2022-09-18 14:33 UTC, bosilca approved these changes

2022-09-18 14:34 UTC, merged