combining two PRs with Friday meeting sweat
ICLDisco/parsec pull request #594
Opened 2023-11-10 21:11 UTC by DSMishler

Combining results from https://github.com/ICLDisco/parsec/pull/561 (started with https://github.com/ICLDisco/parsec/pull/531) and https://github.com/ICLDisco/parsec/pull/573.

These are the changes we developed in our Friday meeting on Nov 10, 2023.

Added -2 as another value for the profiling array. `profiling_array[0] == -2` signifies that nothing has been initialized yet.

Code should now compile in debug mode and properly run. Currently verifying as much.

Also going to ensure this works with most recent version of PaRSEC and DPLASMA.

2023-11-10 21:30 UTC, therault approved these changes
LGTM

2023-11-11 10:03 UTC, devreal requested changes
@DSMishler I can't judge the fix, but: could you please change the commit message to something more descriptive? And if it is two independent changes maybe split them? Also, can we give `-2` a name to avoid magic numbers?

2023-11-11 16:44 UTC, bosilca approved these changes

2023-11-11 16:48 UTC, bosilca commented
@DSMishler I merged the PR that fixes the profiling tests. Please rebase this PR to current HEAD and wait for the CI to complete a test before merging.

2023-11-12 15:35 UTC, merged