This is only to test if environment variables are correctly forwarded…
ICLDisco/parsec pull request #633
Opened 2024-02-07 21:58 UTC by therault

… by the CI when testing

2024-02-07 22:40 UTC, therault commented
It seems ctest, as it is run from the CI, doesn't forward the environment variables passed to it by the shell in CI.

For example, we wrote
```
PARSEC_MCA_device_cuda_enabled=0 ctest ...
```
in `.github/workflows/build_cmake.yml`, but when we test if `PARSEC_MCA_device_cuda_enabled` is defined and to what in a test, we don't find it in the environment. See 
https://github.com/ICLDisco/parsec/actions/runs/7821760842/job/21339489092?pr=633
for an example (the test name was `cuda-disabled-by-default-in-environment`).

I tested the following:
  - if PARSEC_MCA_device_cuda_enabled is found in the environment of processes launched by ctest in CI. Result: no.
  - if we define some variable in the mpiexec command line, does the child process sees that variable. Result: yes.

The reliable way seems to use `set_property(TEST test-name PROPERTY ENVIRONMENT "PARSEC_MCA_device_cuda_enabled=0")` directly in CMake files, when we define the tests.

I will code this in `parsec_addtest`

2024-02-08 00:38 UTC, bosilca commented
If you code this in `add_test` we will never test the accelerators. This should be part of the CI  ...

2024-02-08 00:51 UTC, therault commented
My understanding of MCA is that environment variables are the weakest
selector. When we set the MCA parameter via command line, or when we set
the MCA parameter via the API, this will supersede that environment
variable.

Thus, as written in the comment of the PR, this should not prevent to run
any GPU test, and contrary to the approach where we set environment
variables only in the CI case, that reduces the chance of CI behaving
differently from interactive ctest runs.


On Wed, Feb 7, 2024 at 7:38 PM bosilca ***@***.***> wrote:

> If you code this in add_test we will never test the accelerators. This
> should be part of the CI ...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ICLDisco/parsec/pull/633#issuecomment-1933175147>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABFEZNRZKGXQD2L7UJI264LYSQM7XAVCNFSM6AAAAABC6SYF52VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZTGE3TKMJUG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-09 15:07 UTC, abouteiller requested changes

2024-02-09 15:07 UTC, abouteiller commented on .github/workflows/build_cmake.yml
> -        PARSEC_MCA_device_cuda_memory_use=10
this is also needed to be replicated

2024-02-09 19:58 UTC, abouteiller approved these changes

2024-02-09 21:23 UTC, merged