Add support for batched tasks.
ICLDisco/parsec pull request #668
Opened 2024-09-10 03:51 UTC by bosilca

The idea is the following:
- tasks incarnations (aka. BODY) can be marked with the "batch" property allowing the runtime to provide the task with the entire list of ready tasks of the execution stream instead of just extracting the head.
- this list of ready tasks is in fact a ring, that can then be trimmed by the kernel and divided into the tasks to be batch and the rest. While the batch group will be submitted for execution (user responsibility), the rest of the tasks will be added back into the stream pending list, in the order in which they were provided in the ring. This mechanism also allow the user to reorder the tasks based on some user-level criteria.
- the kernel also needs to provide a callback into the gpu_task complete_stage, such that the runtime can call the specialized function able to complete all batched tasks.

2025-02-26 19:39 UTC, abouteiller commented on parsec/mca/device/device_gpu.c
> +            goto move_forward_with_this_task;
can we avoid using a goto here?

2025-02-26 19:39 UTC, abouteiller commented on parsec/interfaces/ptg/ptg-compiler/jdf2c.c
> +        if (!strncasecmp(type_property->expr->jdf_var, "cuda", 4)  /* for batched */
Looks like a leftover from a prior iteration of that patchset that used the `type=cuda_batched` instead of adding a new `batched` property.

I assume the expectation is that we can have `batched` and `non batched` CUDA bodies simultaneously. Did you test this works?

2026-05-11 13:46 UTC, bosilca commented on parsec/interfaces/ptg/ptg-compiler/jdf2c.c
> +        if (!strncasecmp(type_property->expr->jdf_var, "cuda", 4)  /* for batched */
This was indeed a left over, I will remove it.

For your second question, no we can't have two incarnations of the same device, this would be rejected by the runtime. However, the batched property is just a hint for both the user and the runtime. The runtime does not have to fulfill it in which case it will call the task with a single, singletoned, task each time. If it chooses to provide a batched call, the task will have a chain of tasks as input, and will return a chain of tasks as output. If the user chooses to ignore the batched support it can treat just the current task, and then singleton it before returning.

2026-05-11 15:56 UTC, devreal requested changes

2026-05-11 15:56 UTC, devreal commented on parsec/mca/device/device.c
> +#endif
Why not enabled by default?

2026-05-11 15:56 UTC, devreal commented on parsec/mca/device/device.h
> +#define PARSEC_DEV_CUDA_BATCH ((uint8_t)(1 << 5))
Any reason why we cannot batch on other architectures?

2026-05-11 15:56 UTC, devreal commented on parsec/mca/device/device_gpu.c
> +    PARSEC_LIST_ITEM_SINGLETON((parsec_list_item_t *)task);
That goto is ugly and easy to avoid:

```suggestion
    /* Should we allow the tasks to be batched */
    bool do_batch = false;
#if defined(PARSEC_HAVE_DEV_CAPABILITY_BATCH)
    if (PARSEC_GPU_TASK_TYPE_KERNEL == task->task_type ) {
        assert(task->ec->selected_chore >= 0);
        if( (PARSEC_DEV_CHORE_ALLOW_BATCH & task->ec->task_class->incarnations[task->ec->selected_chore].type) &&
            parsec_mca_device_type_supports_batch(task->ec->selected_device->type) ) {
            /* Don't singleton the task, allowing the kernel to extract the tasks it wants
             * from the task ring, and singleton it or replace it with the aggregated tasks
             * as necessary.
             */
            do_batch = true;
        }
    }
#endif
    if (!do_batch) {
        PARSEC_LIST_ITEM_SINGLETON((parsec_list_item_t *)task);
    }
```

2026-05-11 15:56 UTC, devreal commented on tests/dsl/dtd/dtd_test_simple_gemm.c
> +    *gpu_task = NULL;
I don't like this. The DSL should be required to modify internal data structures. This should be done by the GPU manager instead.

2026-05-11 15:56 UTC, devreal commented on parsec/mca/device/device_gpu.c
> +        }
It would be good to have a STOP signal that can be returned by the callback. If I know I can batch up to 20 tasks but there are hundreds in the queue then I will want to stop after 20 and not look at all of them.

2026-05-11 15:57 UTC, devreal commented
I might have reviewed a stale version (before the last commit). I like the approach and I think we can integrate that into TTG. The docs that were just added should be good to work this out.

2026-05-11 16:02 UTC, bosilca commented on parsec/mca/device/device.c
> +#endif
I'm not 100% sure, but maybe because I somehow feel this doesn't bring much unless the tasks are very small, which is not the default regime where parsec is used. I'm just looking for a reason to turn it on ...

2026-05-11 16:04 UTC, bosilca commented on parsec/mca/device/device.h
> +#define PARSEC_DEV_CUDA_BATCH ((uint8_t)(1 << 5))
it's a leftover from another approach. All devices support batching, CPU and recursive will never let the user do anything meaningful. Getting access to the list of ready_tasks is difficult on these devices, so for now the capability should not be used.

2026-05-11 16:10 UTC, bosilca commented on parsec/mca/device/device_gpu.c
> +    PARSEC_LIST_ITEM_SINGLETON((parsec_list_item_t *)task);
I have no issues with goto, it works great they way they were intended to. However, the code in question got removed, so no need to have this discussion anymore.

2026-05-11 16:10 UTC, bosilca commented on tests/dsl/dtd/dtd_test_simple_gemm.c
> +    *gpu_task = NULL;
I can't do that, the manager is agnostic to whatever "batching" means for the user.

2026-05-11 16:11 UTC, bosilca commented on parsec/mca/device/device_gpu.c
> +        }
It does have that. Return any negative value, it will be pushed back to the user code, and there you handled it as you want.

2026-05-11 16:17 UTC, bosilca commented on parsec/mca/device/device.c
> +#endif
I will merge all these into one and set the default to true. I revisited the code and there is no drawback not cost to do so.

2026-05-11 17:35 UTC, devreal commented on parsec/mca/device/device_gpu.c
> +        rc = callback((parsec_gpu_task_t *)item, batch_head, callback_data);
Should screen for the same task-class as `batch_head` here first? I'm not sure that it makes sense to mix task classes in a batch and it seems error-prone to let the user screen for it.

2026-05-11 17:35 UTC, devreal commented on tests/dsl/dtd/dtd_test_simple_gemm.c
> +    }
I think having an example that actually batches GEMM calls would be helpful. Here is one (untested, written in the browser)

```suggestion
    current_gpu_task = gpu_task;
    // NOTE: assuming all tasks have the same shape. Special handling needed otherwise.
    int m, n, k, mb, nb, kb;
    double** As = malloc(batch_count*sizeof(*As));
    double** Bs = malloc(batch_count*sizeof(*Bs));
    double** Cs = malloc(batch_count*sizeof(*Cs));
    for (int i = 0; i < batch_count; ++i) {
        double *A, *B, *C;
        parsec_task_t *this_task = current_gpu_task->ec;
        struct timeval start, end, diff;
        double delta;
        double *a_gpu, *b_gpu, *c_gpu;

        parsec_dtd_unpack_args(this_task,
                               &A, &B, &C,
                               &m, &n, &k,
                               &mb, &nb, &kb);
        (void)A; (void)B; (void)C;
        As[i] = parsec_dtd_get_dev_ptr(this_task, 0);
        Bs[i] = parsec_dtd_get_dev_ptr(this_task, 1);
        Cs[i] = parsec_dtd_get_dev_ptr(this_task, 2);

        current_gpu_task = (parsec_gpu_task_t *)current_gpu_task->list_item.list_next;
    } while( current_gpu_task != gpu_task );

    gettimeofday(&start, NULL);

    status = cublasDgemmBatched(handle,
                            CUBLAS_OP_N, CUBLAS_OP_N,
                            mb, nb, kb,
                            one_device, As, mb,
                            Bs, kb,
                            one_device, Cs, mb,
                            batch_count);

    gettimeofday(&end, NULL);
    timersub(&end, &start, &diff);
    delta = (double)diff.tv_sec + (double)diff.tv_usec/1e6;
    if(verbose) {
        fprintf(stderr, "GEMM(%d, %d, %d) with tiles of %dx%d, %dx%d, %dx%d on node %d, GPU %s submitted in %g s%s\n",
                m, n, k, mb, kb, kb, nb, mb, kb,
                this_task->taskpool->context->my_rank,
                gpu_stream->name, delta,
                batch_count > 1 ? " as part of a batch" : "");
    }

    PARSEC_CUDA_CHECK_ERROR("cublasDgemmBatched", status,
                            { return PARSEC_HOOK_RETURN_ERROR; });

    if( verbose && batch_count > 1 ) {
        fprintf(stderr, "Submitted %d batched GEMM tasks on GPU stream %s\n",
                batch_count, gpu_stream->name);
    }
```

2026-05-11 17:35 UTC, devreal commented on docs/doxygen/task-batching.md
> +}
It's not clear how PTG tasks can actually batch kernel invocations. Simply stringing kernels together on the same stream won't save much.

2026-05-11 18:10 UTC, bosilca commented on docs/doxygen/task-batching.md
> +}
The same way as DTD tasks, and the same way we did two years ago for the GB submission.

2026-05-11 18:11 UTC, bosilca commented on tests/dsl/dtd/dtd_test_simple_gemm.c
> +    }
I'm sorry but this is not parsec role to batch gemm tasks. There is a clear way to do it, an example on how to do it. That should be more than enough for any PR !

That being said, this would be a really nice addition to DPLASMA ! Looking forward to your PR.

2026-05-11 18:13 UTC, bosilca commented on parsec/mca/device/device_gpu.c
> +        rc = callback((parsec_gpu_task_t *)item, batch_head, callback_data);
Not the runtime job to do so. We can impose whatever rules we want, but my goal here is to let the user drive this.

2026-05-11 19:05 UTC, devreal commented on tests/dsl/dtd/dtd_test_simple_gemm.c
> +    }
What is the benefit of "batching" kernels one by one into the same stream vs submitting them the same way we do today? I don't see how the above will yield any benefits so it's not a good example.

2026-05-11 19:05 UTC, devreal commented on docs/doxygen/task-batching.md
> +}
GB submissions are not part of the docs.

2026-05-11 19:16 UTC, bosilca commented on docs/doxygen/task-batching.md
> +}
This PR has been lingering here for a very long time. Let's get it in.

2026-05-11 19:21 UTC, devreal approved these changes
I guess we'll see benefits in DPLASMA once it's picked up there (not volunteering by any means...)

2026-05-11 20:25 UTC, merged

2026-05-11 20:29 UTC, bosilca commented on tests/dsl/dtd/dtd_test_simple_gemm.c
> +    }
In the worst case we are saving a CUDA event recording and tracking per "batched" task. Something you were very supportive for the PR that saved one event for tasks "with all input arguments available". And here we might save more than one, so even in the worst case still a positive outcome.

2026-05-11 20:43 UTC, devreal commented on tests/dsl/dtd/dtd_test_simple_gemm.c
> +    }
Not quite. Here we're saving one at most per task (the event on the execution stream) but still have the input and output ones for each task. In #681 we are potentially saving two per task (the input and the output events). Combined, this can significantly reduce the number of events overall.

2026-05-11 21:07 UTC, bosilca commented on tests/dsl/dtd/dtd_test_simple_gemm.c
> +    }
There is absolutely no requirement to have the input/output event for each task. This optimization is actually complementary to the one in #681.