Apply does not release user-defined memory
ICLDisco/parsec pull request #676
Opened 2024-10-08 17:02 UTC by QingleiCao

https://github.com/ICLDisco/parsec/issues/675

2024-10-08 17:17 UTC, devreal approved these changes
Sounds reasonable not to transfer ownership to `parsec_apply`

2024-10-08 17:36 UTC, bosilca approved these changes

2024-10-11 14:41 UTC, abouteiller approved these changes

2024-10-11 14:44 UTC, abouteiller commented on tests/apps/stencil/testing_stencil_1D.c
>                    (parsec_tiled_matrix_unary_op_t)stencil_1D_init_ops, op_args);
```suggestion
                  (parsec_tiled_matrix_unary_op_t)stencil_1D_init_ops, &R);
```

2024-10-11 15:56 UTC, devreal requested changes

2024-10-11 15:56 UTC, devreal commented on tests/collections/redistribute/testing_redistribute_random.c
> +        int *op_args_dtd = 0;
```suggestion
        int op_args_dtd = 0; 
```

2024-10-11 15:58 UTC, QingleiCao commented on tests/collections/redistribute/testing_redistribute_random.c
> +        int *op_args_dtd = 0;
fixed. thanks

2024-10-11 16:00 UTC, devreal approved these changes

2024-10-11 17:32 UTC, therault approved these changes

2024-10-11 17:33 UTC, merged