Derive the device_task_t from a parsec_object_t
ICLDisco/parsec pull request #694
Opened 2024-11-06 22:22 UTC by bosilca

Introduce the parsec_gpu_flow_info_s info structure to combine the flow information needed by the GPU code.

Allow the standard device tasks (aka. parsec_gpu_dsl_task_t) to contain the flow_info array inside the task, while allowing other DSL to have their own type of device task (derived from parsec_gpu_task_t)

Enhance the mechanism to release the device tasks via the release_device_task function pointer. The device code will call this function to let the DSL decide how to device task release should be handled. Some DSL (PTG and DTD as of now) will call OBJ_RELEASE on it (and the free is automatic), while others (TTG as an example) will have its own handling.

2024-12-12 12:24 UTC, devreal commented on parsec/mca/device/device_gpu.c
> +    gpu_task->release_device_task(gpu_task);
Please don't. We want to be able to embed the device task structure into another structure (the task) in TTG. Using `OBJ_RELEASE` would break that.

2024-12-12 13:42 UTC, abouteiller commented on parsec/mca/device/device_gpu.c
> +    gpu_task->release_device_task(gpu_task);
Wouldn't OBJ_DESTRUCT serve that case?

2024-12-12 17:32 UTC, abouteiller commented on parsec/mca/device/device_gpu.c
> +    gpu_task->release_device_task(gpu_task);
We need to be able to let the TTG DSL know that it is now safe to release the gpu task, which is itself a static member of a DSL specific structure. Hence, we need to have that callback that lets the DSL customize what happens when the gpu task is ready to be released (as seen from parsec perspective).

2024-12-12 19:08 UTC, bosilca commented on parsec/data_internal.h
> +    size_t                     span;          /* size in bytes of the memory layout */
The extent in MPI is defined as the difference between the UB and LB. Here we have no LB, or more correctly it is assumed 0. Moreover, this is related to the entire type including the count, so it is again not technically `extent`.

2024-12-12 20:48 UTC, abouteiller approved these changes, later dismissed

2024-12-12 20:52 UTC, abouteiller commented
stress:gpu failed, I think that's new

2025-01-02 17:41 UTC, abouteiller commented
wip: lldb output from `lldb` seems to indicate that we need to re-zero dsl-tasks after first use (dplasma 2gpu will fail rarely and randomly with this stack trace) 

```
PARSEC_MCA_device_cuda_memory_use=10 PARSEC_MCA_device_cuda_enabled=0 PMIX_MCA_psec='' /usr/bin/srun --pty -wleconte  "-n1" lldb --  "tests/testing_spotrf" "-N" "4600" "-t" "320" "-x" "-v=5" "-g" "2" "--" "--mca" "device_cuda_memory_number_of_blocks" "4096" --mca device_show_capabilities 1
i@00000 Dev GPU    cuda(0) : Tesla V100-SXM2-32GB 32GB [pci 6:0.0]
i@00000 Dev GPU    cuda(1) : Tesla V100-SXM2-32GB 32GB [pci 7:0.0]
i@00000 Dev 0    cpu-cores : Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
#+++++ nodes x cores + gpu  : 1 x 40 + 2 (40+2)
#+++++ thread mode          : THREAD_SERIALIZED
* thread #28, name = 'testing_spotrf', stop reason = signal SIGSEGV: invalid permissions for mapped object (fault address: * thread #28, name = 'testing_spotrf', stop reason = signal SIGSEGV: invalid permissions for mapped object (fault address: 0xeeaae0)
  * frame #0: 0x0000000000eeaae0
    frame #1: 0x00007ffff3d4a7a4 libparsec.so.4`parsec_device_progress_stream(gpu_device=0x0000000000f13ab0, stream=0x0000000000f13f68, progress_fct=(libparsec.so.4`parsec_device_kernel_pop at device_gpu.c:2130), task=0x00007ffe04002160, out_task=0x00007ffe08fe2420) at device_gpu.c:1892:22
    frame #2: 0x00007ffff3d49c2c libparsec.so.4`parsec_device_kernel_scheduler(module=0x0000000000f13ab0, es=0x00007ffdd4000bf0, _gpu_task=0x00007ffe1c001e10) at device_gpu.c:2605:10
    frame #3: 0x00007ffff5458440 libdplasma.so.2`hook_of_spotrf_L_potrf_ssyrk_CUDA(es=0x00007ffdd4000bf0, this_task=0x00007ffdd4005c20) at spotrf_L.c:4204:10
    frame #4: 0x00007ffff3d22d19 libparsec.so.4`__parsec_execute(es=0x00007ffdd4000bf0, task=0x00007ffdd4005c20) at scheduling.c:152:10
    frame #5: 0x00007ffff3d23bfe libparsec.so.4`__parsec_task_progress(es=0x00007ffdd4000bf0, 
   1889             assert( PARSEC_HOOK_RETURN_ASYNC != task->last_status );
   1890             rc = PARSEC_HOOK_RETURN_DONE;
   1891             if (task->complete_stage)
-> 1892                 rc = task->complete_stage(gpu_device, out_task, stream);
   1893             /* the task can be withdrawn by the system */
   1894             return rc;
   1895         }
(lldb) p *task
(parsec_gpu_task_t) {
  list_item = {
    super = {
      obj_magic_id = 16046253926196952813
      obj_class = 0x00007ffff3e622f0
      obj_reference_count = 1
      cls_init_file_name = 0x00007ffff3e2159e "/home/bouteill/parsec/dplasma/parsec/parsec/mca/device/device_gpu.c"
      cls_init_lineno = 1620
    }
    list_next = 0x00007ffe04002160
    list_prev = 0x00007ffe04002160
    aba_key = 0
    refcount = 0
    belong_to = 0x00007ffe04002160
  }
  task_type = 32768
  pushout = 63432
  last_status = 0
  submit = 0x0000000000064000
  complete_stage = 0x0000000000eeaae0
  stage_in = 0x00007ffff3d480a0 (libparsec.so.4`parsec_default_gpu_stage_in at device_gpu.c:1196)
  stage_out = 0x00007ffff3d48290 (libparsec.so.4`parsec_default_gpu_stage_out at device_gpu.c:1246)
  release_device_task = 0x00007ffff3d4d380 (libparsec.so.4`parsec_device_release_gpu_task at device_gpu.c:49)
   = {
     = {
      ec = 0x00007ffe04002480
      last_data_check_epoch = 33
      nb_flows = 0
      flow_info = 0x00007ffe040021f8
    }
     = {
      copy = 0x00007ffe04002480
    }
  }
```
a number of fields in the task structure look uninitialized, these used to be `calloced` so implicit zeroed, so that's probable cause

2025-01-02 20:29 UTC, abouteiller commented
> wip: lldb output from `lldb` seems to indicate that we need to re-zero dsl-tasks after first use (dplasma 2gpu will fail rarely and randomly with this stack trace)
> 
> ```
> PARSEC_MCA_device_cuda_memory_use=10 PARSEC_MCA_device_cuda_enabled=0 PMIX_MCA_psec='' /usr/bin/srun --pty -wleconte  "-n1" lldb --  "tests/testing_spotrf" "-N" "4600" "-t" "320" "-x" "-v=5" "-g" "2" "--" "--mca" "device_cuda_memory_number_of_blocks" "4096" --mca device_show_capabilities 1
> i@00000 Dev GPU    cuda(0) : Tesla V100-SXM2-32GB 32GB [pci 6:0.0]
> i@00000 Dev GPU    cuda(1) : Tesla V100-SXM2-32GB 32GB [pci 7:0.0]
> i@00000 Dev 0    cpu-cores : Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
> #+++++ nodes x cores + gpu  : 1 x 40 + 2 (40+2)
> #+++++ thread mode          : THREAD_SERIALIZED
> * thread #28, name = 'testing_spotrf', stop reason = signal SIGSEGV: invalid permissions for mapped object (fault address: * thread #28, name = 'testing_spotrf', stop reason = signal SIGSEGV: invalid permissions for mapped object (fault address: 0xeeaae0)
>   * frame #0: 0x0000000000eeaae0
>     frame #1: 0x00007ffff3d4a7a4 libparsec.so.4`parsec_device_progress_stream(gpu_device=0x0000000000f13ab0, stream=0x0000000000f13f68, progress_fct=(libparsec.so.4`parsec_device_kernel_pop at device_gpu.c:2130), task=0x00007ffe04002160, out_task=0x00007ffe08fe2420) at device_gpu.c:1892:22
>     frame #2: 0x00007ffff3d49c2c libparsec.so.4`parsec_device_kernel_scheduler(module=0x0000000000f13ab0, es=0x00007ffdd4000bf0, _gpu_task=0x00007ffe1c001e10) at device_gpu.c:2605:10
>     frame #3: 0x00007ffff5458440 libdplasma.so.2`hook_of_spotrf_L_potrf_ssyrk_CUDA(es=0x00007ffdd4000bf0, this_task=0x00007ffdd4005c20) at spotrf_L.c:4204:10
>     frame #4: 0x00007ffff3d22d19 libparsec.so.4`__parsec_execute(es=0x00007ffdd4000bf0, task=0x00007ffdd4005c20) at scheduling.c:152:10
>     frame #5: 0x00007ffff3d23bfe libparsec.so.4`__parsec_task_progress(es=0x00007ffdd4000bf0, 
>    1889             assert( PARSEC_HOOK_RETURN_ASYNC != task->last_status );
>    1890             rc = PARSEC_HOOK_RETURN_DONE;
>    1891             if (task->complete_stage)
> -> 1892                 rc = task->complete_stage(gpu_device, out_task, stream);
>    1893             /* the task can be withdrawn by the system */
>    1894             return rc;
>    1895         }
> (lldb) p *task
> (parsec_gpu_task_t) {
>   list_item = {
>     super = {
>       obj_magic_id = 16046253926196952813
>       obj_class = 0x00007ffff3e622f0
>       obj_reference_count = 1
>       cls_init_file_name = 0x00007ffff3e2159e "/home/bouteill/parsec/dplasma/parsec/parsec/mca/device/device_gpu.c"
>       cls_init_lineno = 1620
>     }
>     list_next = 0x00007ffe04002160
>     list_prev = 0x00007ffe04002160
>     aba_key = 0
>     refcount = 0
>     belong_to = 0x00007ffe04002160
>   }
>   task_type = 32768
>   pushout = 63432
>   last_status = 0
>   submit = 0x0000000000064000
>   complete_stage = 0x0000000000eeaae0
>   stage_in = 0x00007ffff3d480a0 (libparsec.so.4`parsec_default_gpu_stage_in at device_gpu.c:1196)
>   stage_out = 0x00007ffff3d48290 (libparsec.so.4`parsec_default_gpu_stage_out at device_gpu.c:1246)
>   release_device_task = 0x00007ffff3d4d380 (libparsec.so.4`parsec_device_release_gpu_task at device_gpu.c:49)
>    = {
>      = {
>       ec = 0x00007ffe04002480
>       last_data_check_epoch = 33
>       nb_flows = 0
>       flow_info = 0x00007ffe040021f8
>     }
>      = {
>       copy = 0x00007ffe04002480
>     }
>   }
> ```
> 
> a number of fields in the task structure look uninitialized, these used to be `calloced` so implicit zeroed, so that's probable cause

2025-01-02 20:32 UTC, abouteiller commented
New problem: all tests with 2gpus appear to leak/over-retain gpu memory 

```
237/441 Test #237: dplasma_cgemm_2gpu_cuda_shm .....................................***Failed    1.78 sec
W@00000 /!\ DEBUG LEVEL WILL PROBABLY REDUCE THE PERFORMANCE OF THIS RUN /!\.
#+++++ cores detected       : 40
#+++++ nodes x cores + gpu  : 1 x 40 + 2 (40+2)
#+++++ thread mode          : THREAD_SERIALIZED
#+++++ P x Q                : 1 x 1 (1/1)
#+++++ M x N x K|NRHS       : 1940 x 1940 x 1940
#+++++ LDA , LDB , LDC      : 1940 , 1940 , 1940
#+++++ MB x NB              : 320 x 320
[   0] TIME(s)      0.43082 : PaRSEC initialized
***************************************************
 ----- TESTING CGEMM (N, N) --------
Generate matrices ... Done
Compute ... ... [****] TIME(s)      0.03400 : cgemm     PxQxg=   1 1   2 NB=  320 N=    1940 :    1718.191219 gflops - ENQ&PROG&DEST      0.04932 :    1184.270940 gflops - ENQ      0.01127 - DEST      0.00406
+---------------------------------------------------------------------------------------------------------------------------------------------+
|         |                    |                       Data In                              |                    Data Out                     |
|Rank   0 |  # KERNEL |    %   |  Required  |    Transfered H2D(%)  |    Transfered D2D(%)  |  Required  |      Transfered(%)  |   Evictions  |
|---------|-----------|--------|------------|-----------------------|-----------------------|------------|---------------------|--------------|
|  Dev  0 |       198 |  36.60 |     0.00 B |       0.00 B(   nan)  |       0.00 B(   nan)  |     0.00 B |     0.00 B(   nan)  |           0  | cpu-cores
|  Dev  1 |       196 |  36.23 |   459.38MB |      61.72MB( 13.44)  |      20.31MB(  4.42)  |   153.12MB |    21.88MB( 14.29)  |           0  | cuda(0)
|  Dev  2 |       147 |  27.17 |   344.53MB |      60.94MB( 17.69)  |      10.16MB(  2.95)  |   114.84MB |    16.41MB( 14.29)  |           0  | cuda(1)
|---------|-----------|--------|------------|-----------------------|-----------------------|------------|---------------------|--------------|
|All Devs |       541 | 100.00 |   803.91MB |     153.12MB( 19.05)  |      30.47MB(  3.79)  |   267.97MB |    38.28MB( 14.29)  |           0  |
+---------------------------------------------------------------------------------------------------------------------------------------------+
<DartMeasurement name="performance" type="numeric/double"
                 encoding="none" compression="none">
1718.19
</DartMeasurement>
W@00000 GPU[1:cuda(0)] memory leak detected: 12582912 bytes still allocated on GPU
D@00000 flush_lru: free: 16 units (8388608 bytes) from 0x7f618e000000 to 0x7f618e7fffff @zone_debug:217
D@00000 flush_lru: used: 2 units (1048576 bytes) from 0x7f618e800000 to 0x7f618e8fffff @zone_debug:224
D@00000 flush_lru: free: 24 units (12582912 bytes) from 0x7f618e900000 to 0x7f618f4fffff @zone_debug:217
D@00000 flush_lru: used: 2 units (1048576 bytes) from 0x7f618f500000 to 0x7f618f5fffff @zone_debug:224
D@00000 flush_lru: free: 36 units (18874368 bytes) from 0x7f618f600000 to 0x7f61907fffff @zone_debug:217
D@00000 flush_lru: used: 2 units (1048576 bytes) from 0x7f6190800000 to 0x7f61908fffff @zone_debug:224
D@00000 flush_lru: used: 2 units (1048576 bytes) from 0x7f6190900000 to 0x7f61909fffff @zone_debug:224
D@00000 flush_lru: used: 2 units (1048576 bytes) from 0x7f6190a00000 to 0x7f6190afffff @zone_debug:224
D@00000 flush_lru: used: 2 units (1048576 bytes) from 0x7f6190b00000 to 0x7f6190bfffff @zone_debug:224
D@00000 flush_lru: used: 2 units (1048576 bytes) from 0x7f6190c00000 to 0x7f6190cfffff @zone_debug:224
D@00000 flush_lru: free: 2 units (1048576 bytes) from 0x7f6190d00000 to 0x7f6190dfffff @zone_debug:217
D@00000 flush_lru: used: 2 units (1048576 bytes) from 0x7f6190e00000 to 0x7f6190efffff @zone_debug:224
D@00000 flush_lru: used: 2 units (1048576 bytes) from 0x7f6190f00000 to 0x7f6190ffffff @zone_debug:224
D@00000 flush_lru: free: 6 units (3145728 bytes) from 0x7f6191000000 to 0x7f61912fffff @zone_debug:217
D@00000 flush_lru: used: 2 units (1048576 bytes) from 0x7f6191300000 to 0x7f61913fffff @zone_debug:224
D@00000 flush_lru: used: 2 units (1048576 bytes) from 0x7f6191400000 to 0x7f61914fffff @zone_debug:224
D@00000 flush_lru: free: 18 units (9437184 bytes) from 0x7f6191500000 to 0x7f6191dfffff @zone_debug:217
D@00000 flush_lru: used: 2 units (1048576 bytes) from 0x7f6191e00000 to 0x7f6191efffff @zone_debug:224
D@00000 flush_lru: free: 3970 units (2081423360 bytes) from 0x7f6191f00000 to 0x7f620dffffff @zone_debug:217
testing_cgemm: /home/bouteill/parsec/dplasma/parsec/parsec/mca/device/device_gpu.c:831: int parsec_device_flush_lru(parsec_device_module_t *): Assertion `!in_use' failed.
[leconte:1749985] *** Process received signal ***
[leconte:1749985] Signal: Aborted (6)
[leconte:1749985] Signal code:  (-6)
[leconte:1749985] [ 0] /lib64/libc.so.6(+0x3e730)[0x7f62530f0730]
[leconte:1749985] [ 1] /lib64/libc.so.6(+0x8ba6c)[0x7f625313da6c]
[leconte:1749985] [ 2] /lib64/libc.so.6(raise+0x16)[0x7f62530f0686]
[leconte:1749985] [ 3] /lib64/libc.so.6(abort+0xd3)[0x7f62530da833]
[leconte:1749985] [ 4] /lib64/libc.so.6(+0x2875b)[0x7f62530da75b]
[leconte:1749985] [ 5] /lib64/libc.so.6(+0x373c6)[0x7f62530e93c6]
[leconte:1749985] [ 6] /home/bouteill/parsec/dplasma/build.cuda/parsec/parsec/libparsec.so.4(parsec_device_flush_lru+0x12c)[0x7f62a6ff7fbc]
[leconte:1749985] [ 7] /home/bouteill/parsec/dplasma/build.cuda/parsec/parsec/libparsec.so.4(parsec_devices_release_memory+0x57)[0x7f62a6ff5047]
[leconte:1749985] [ 8] /home/bouteill/parsec/dplasma/build.cuda/tests/./testing_cgemm[0x40550c]
[leconte:1749985] [ 9] /lib64/libc.so.6(+0x295d0)[0x7f62530db5d0]
[leconte:1749985] [10] /lib64/libc.so.6(__libc_start_main+0x80)[0x7f62530db680]
[leconte:1749985] [11] /home/bouteill/parsec/dplasma/build.cuda/tests/./testing_cgemm[0x4023f5]
[leconte:1749985] *** End of error message ***
srun: error: leconte: task 0: Aborted
```

2025-01-10 17:24 UTC, devreal requested changes

2025-01-10 17:24 UTC, devreal commented on parsec/mca/device/device_gpu.c
> +    gpu_task->last_data_check_epoch = 0;
This is wrong because it will deadlock on the first GPU task submitted.

```suggestion
    gpu_task->last_data_check_epoch = (uint64_t)-1;
```

2025-01-10 17:33 UTC, devreal commented
This is now used in https://github.com/TESSEorg/ttg/pull/307 and seems to work (except for https://github.com/ICLDisco/parsec/pull/694#discussion_r1910691981). I'd like to see this go in asap.

2025-01-10 20:15 UTC, bosilca commented
I saw a notification with a lldb stack trace but I can't find it here. Weird! Anyway, it seemed to indicate that the `complete_stage` was pointing to an incorrect location.

2025-02-04 18:47 UTC, abouteiller commented
> I saw a notification with a lldb stack trace but I can't find it here. Weird! Anyway, it seemed to indicate that the `complete_stage` was pointing to an incorrect location.

https://github.com/ICLDisco/parsec/pull/694#issuecomment-2568343393

2025-02-13 15:47 UTC, abouteiller commented on parsec/interfaces/ptg/ptg-compiler/jdf2c.c
>              "  gpu_task->last_data_check_epoch = -1;  /* force at least one validation for the task */\n",
remove

2025-02-13 15:48 UTC, abouteiller commented on parsec/interfaces/dtd/insert_function.c
>      gpu_task->last_data_check_epoch = -1;       /* force at least one validation for the task */
remove

2025-02-13 15:48 UTC, abouteiller commented on parsec/mca/device/device_gpu.c
> +    gpu_task->last_data_check_epoch = 0;
max_int

2026-05-20 20:04 UTC, merged